---
title: "test"
author: "Maxwel Coura Oliveira"
date: "6/29/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(
  warning = FALSE,
  error = FALSE,
  echo = FALSE
)
```


```{r include=FALSE}
library(tidyverse)
library(tidymodels)
library(purrr)
library(ggtext)
library(kableExtra)
library(tidytext)
```

```{r}
Data2 = read.csv("Soil2.csv")
glimpse(Data2)
```


```{r}
Data = read.csv("Soil1.csv")
glimpse(Data)
```

```{r}
sum(is.na(data))
```



```{r}
data <- Data2 %>% 
  filter(trt != "check") %>% 
   mutate_if(is.character, as.factor) #%>% 
#  filter(!is.na(biopercent))
```

```{r}
ggplot(data) + aes(y=biopercent, x=GDD) + geom_smooth(method="lm") + geom_point(alpha=0.1) +
  facet_grid(spec~trt) 
```

```{r}
lm_mod <- 
  linear_reg() %>% 
  set_engine("lm")
```


```{r}
lm_fit <- 
  lm_mod %>% 
  fit(biopercent ~ GDD * spec * trt, data = data)

tidy(lm_fit)
```


```{r}
# Here you select the GDD you want. For instance, if you want to see the residual at the end season, you add GDD>1000
new_points <- expand.grid(GDD = c(100, 500, 900), 
                          trt = c("clas", "dual", "first", "out", "purs", "sharp", "spart", "tric", "valor", "war", "zid"), spec= c("fox", "pal", "rad", "rye"))
new_points
```

```{r}
#Getting predited values
mean_pred <- predict(lm_fit, new_data = new_points)
mean_pred
```

```{r}
#Getting conf intervals
conf_int_pred <- predict(lm_fit, 
                         new_data = new_points, 
                         type = "conf_int")
conf_int_pred
```




```{r}
# Plotting biomass (% untreated) at GDD = 1000 (your choice)
plot_data <- 
  new_points %>% 
  bind_cols(mean_pred) %>% 
  bind_cols(conf_int_pred)

# and plot:
ggplot(plot_data, aes(x = fct_reorder(trt, .pred))) + facet_grid(~spec) +
  geom_point(aes(y = .pred)) + coord_flip() +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + 
  labs(y = "Biomass (% of untreated)")
```

```{r}
new_data <- plot_data %>% 
  mutate(trt = fct_recode(trt,
                          "Chlorimuron-ethyl (2)" = "clas", 
                          "Cloransulam-methyl (2)" = "first", 
                          "Imazethapyr (2)" = "purs", 
                          "Metribuzin (5)" = "tric", 
                          "Sulfentrazone (14)" = "spart",  
                          "Flumioxazin (14)" = "valor", 
                          "Saflufenacil (14)" = "sharp", 
                          "Dimethenamid-P (14)" = "out", 
                          "*S*-metolachlor (15)" = "dual", 
                          "Acetochlor (15)" = "war", 
                          "Pyroxasulfone (15)" = "zid")) %>% 
  mutate(species = fct_recode(spec,
                               "Giant foxtail" = "fox",
                               "Palmer amaranth" = "pal",
                               "Radish" = "rad",
                               "Cereal rye" = "rye")) %>% 
  mutate(GDD = as.factor(GDD), 
         GDD = fct_recode(GDD,
                          "100 GDD" = "100",
                          "500 GDD" = "500",
                          "900 GDD" = "900"
         )) %>% 
  group_by(spec, GDD) %>% 
  mutate(GDD = as.factor(GDD),
           trt = fct_reorder(trt, .pred))
```


```{r}
p1 <- new_data %>% 
  filter(species == "Palmer amaranth") %>% 
  group_by(spec, GDD) %>% 
  mutate(GDD = as.factor(GDD),
           trt = reorder_within(trt, by = .pred, within = GDD)) %>% 
ggplot(aes(x = trt, y = .pred, color = .pred)) + 
  geom_point(size = 2, stroke= 1) + 
  scale_x_reordered() +
  scale_color_gradient(name = "", low = "red", high = "limegreen",
                       limits = c(0, 100), breaks=c(0, 50 ,100),
                       labels= c("High injury", "", "Low injury")) +
  facet_grid(GDD ~ species, scales = "free") + 
  coord_flip() + 
  theme_bw() +
  scale_y_continuous(limits = c(-2,118), breaks = c(0 ,25, 50, 75, 100)) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + theme(panel.grid = element_blank()) +
  labs(x= "", y = "Biomass (% nontreated control)") + 
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", color = "black",
                                  size = 12),
        strip.text.y = element_text(face = "bold", color = "grey30",
                                  size = 12),
        axis.text.y = element_markdown(),
        strip.background = element_rect(fill = "grey90")) +
  ggsave("Figure 6.pdf", width = 4, height = 6, dpi=600)
```

```{r}
p2 <- new_data %>% 
  filter(species == "Giant foxtail") %>% 
  group_by(spec, GDD) %>% 
  mutate(GDD = as.factor(GDD),
           trt = reorder_within(trt, by = .pred, within = GDD)) %>% 
ggplot(aes(x = trt, y = .pred, color = .pred)) + 
  geom_point(size = 2, stroke= 1) + 
  scale_x_reordered() +
  scale_color_gradient(name = "", low = "red", high = "limegreen",
                       limits = c(0, 100), breaks=c(0, 50 ,100),
                       labels= c("High injury", "", "Low injury")) +
  facet_grid(GDD ~ species, scales = "free") + 
  coord_flip() + 
  theme_bw() +
  scale_y_continuous(limits = c(-2,118), breaks = c(0 ,25, 50, 75, 100)) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + theme(panel.grid = element_blank()) +
  labs(x= "", y = "Biomass (% nontreated control)") + 
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", color = "black",
                                  size = 12),
        strip.text.y = element_text(face = "bold", color = "grey30",
                                  size = 12),
        axis.text.y = element_markdown(),
        strip.background = element_rect(fill = "grey90")) +
  ggsave("Figure 7.pdf", width = 4, height = 6, dpi=600)
```






```{r}
p3 <- new_data %>% 
  filter(species == "Radish") %>% 
  group_by(spec, GDD) %>% 
  mutate(GDD = as.factor(GDD),
           trt = reorder_within(trt, by = .pred, within = GDD)) %>% 
  mutate(.pred = if_else(.pred >= 100, 100, .pred)) %>% 
  mutate(.pred_lower = case_when(
    .pred == 100.00000 ~  91.23024,
    TRUE                    ~ .pred_lower)) %>% 
  mutate(.pred_upper = case_when(
    .pred == 100.00000 ~  108.5829,
    TRUE                    ~ .pred_upper)) %>% 
ggplot(aes(x = trt, y = .pred, color = .pred)) + 
  geom_point(size = 2, stroke= 1) +  
  scale_x_reordered() +
  scale_color_gradient(name = "", low = "red", high = "limegreen",
                       limits = c(0, 100), breaks=c(0, 50 ,100),
                       labels= c("High injury", "", "Low injury")) +
  facet_grid(GDD ~ species, scales = "free") + 
  coord_flip() + 
  theme_bw() +
  scale_y_continuous(limits = c(-2,118), breaks = c(0 ,25, 50, 75, 100)) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + theme(panel.grid = element_blank()) +
  labs(x= "", y = "Biomass (% nontreated control)") + 
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", color = "black",
                                  size = 12),
        strip.text.y = element_text(face = "bold", color = "grey30",
                                  size = 12),
        axis.text.y = element_markdown(),
        strip.background = element_rect(fill = "grey90")) +
  ggsave("Figure 8.pdf", width = 4, height = 6, dpi=600)
```

```{r}
p4 <- new_data %>% 
  filter(species == "Cereal rye") %>% 
  group_by(spec, GDD) %>% 
  mutate(GDD = as.factor(GDD),
           trt = reorder_within(trt, by = .pred, within = GDD)) %>% 
ggplot(aes(x = trt, y = .pred, color = .pred)) + 
  geom_point(size = 2, stroke= 1) + 
  scale_x_reordered() +
  scale_color_gradient(name = "", low = "red", high = "limegreen",
                       limits = c(0, 100), breaks=c(0, 50 ,100),
                       labels= c("High injury", "", "Low injury")) +
  facet_grid(GDD ~ species, scales = "free") + 
  coord_flip() + 
  theme_bw() +
  scale_y_continuous(limits = c(-2,118), breaks = c(0 ,25, 50, 75, 100)) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + theme(panel.grid = element_blank()) +
  labs(x= "", y = "Biomass (% nontreated control)") + 
  theme(legend.position = "bottom", 
        strip.text = element_text(face = "bold", color = "black",
                                  size = 12),
        strip.text.y = element_text(face = "bold", color = "grey30",
                                  size = 12),
        axis.text.y = element_markdown(),
        strip.background = element_rect(fill = "grey90")) +
  ggsave("Figure 9.pdf", width = 4, height = 6, dpi=600)
```


```{r}
library(ggpubr)
ggarrange(p1, p2, p3, p4, nrow=1, common.legend = TRUE, legend="bottom")
```



```{r}
f3 <- p1 | p2 | p3 | p4 +
  plot_annotation(tag_levels = 'A') &
  plot_layout(guides = "collect") & theme(legend.position = 'bottom') & 
  scale_colour_continuous(limits = c(0, 100))
  ggsave("Figura_3.pdf", width = 15, height = 7, dpi = 600, f3)
```











#Optimazing your model fit

```{r}
# Nesting data
nested_data <- data %>% 
  group_by(trt, spec) %>% 
  nest()

nested_data
```

```{r}
# Fitting linear models
nested_models <- nested_data %>% 
  mutate(model = map(data, ~ lm(biopercent ~ GDD, data = .x))) 
nested_models
```

```{r}
# Display estimated parameters, associated statistics, confidence intervals
nested_models %>% 
  mutate(coefs = map(model, tidy, conf.int = TRUE)) %>% 
  unnest(coefs)
```

```{r}
# Extracting R squared statistic for each model
nested_models %>% 
  mutate(metrics = map(model, glance)) %>% 
  unnest(metrics) %>% 
  select(trt:r.squared) %>% 
  arrange(desc(r.squared)) # Arranging by "best" R squared
```




